# Generated by Django 2.2.7 on 2019-12-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.CharField(help_text='Unique Squirrel ID', max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=20, help_text='Latitude', max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, help_text='Longitude', max_digits=25)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=50)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=50)),
                ('color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=50)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=50)),
                ('specific_location', models.CharField(blank=True, help_text='Specific Location', max_length=255)),
                ('running', models.BooleanField(default=False, help_text='Running')),
                ('chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('eating', models.BooleanField(default=False, help_text='Eating')),
                ('foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('other_activities', models.CharField(blank=True, help_text='Other Activities', max_length=255)),
                ('kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('moans', models.BooleanField(default=False, help_text='Moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Tail flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Tail twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('runs_from', models.BooleanField(default=False, help_text='Runs from')),
            ],
        ),
    ]
